#!/bin/bash

[ -z "$XRESOURCES" ] && {
	XRES="$(eval echo ~$USER)/.Xresources"
} || {
	XRES=$XRESOURCES
}

[ -f "~/.cache/xgrab-var" ] || [ -f "~/.cache/xgrab-res" ] && {
	msg "Cache files missing! Making them!" warning
}

IFS=""
TYPE=""
GET="$2"
REMOVE='$1="";'

get() {
	[ $1 == "var" ] && {
		REMOVE='$1=""; $2="";'
	}
	
	[ ! -z "$2" ] && {
		GET="$2"
	}

	cat ~/.cache/xgrab-$1 | grep $GET | awk "{ $REMOVE; print }" | sed "s/^[ \t]*//" | sed 1q
}

case $1 in
	"-v")
		TYPE="var"
		;;
	"-r")
		TYPE="res"
		;;
	"-m")
		RESOURCES="$(cat $XRES | grep -v '!' | sed '/^$/d')"
		echo $RESOURCES | grep define > $CACHE_FOLDER/xgrab-var.tmp
		echo $RESOURCES | grep -v '#' > $CACHE_FOLDER/xgrab-res.tmp

		mv $CACHE_FOLDER/xgrab-var.tmp $CACHE_FOLDER/xgrab-var
		mv $CACHE_FOLDER/xgrab-res.tmp $CACHE_FOLDER/xgrab-res
		;;
	*)
		msg "You need to specify the type of resource" error
		;;
esac

[ "$TYPE" = "var" ] && {
	NUM='$2'
	REMOVEOTHER="\$1=\"\";"
	REMOVE="\$1=\"\";\$2=\"\""
} || {
	NUM='$1'
	REMOVEOTHER=""
	REMOVE="\$1=\"\""
}

c() {
	cat ~/.cache/xgrab-$TYPE | sed 's/^[ \t]*//;s/[ \t]*$//'
}

case $2 in
	"-l")
		c | awk "{ print $NUM }"
		;;
	"-ll")
		c | awk "{ $REMOVE; print }"
		;;
	"-lll")
		c | awk "{ $REMOVEOTHER print }"
		;;
	*)
		for i in ${@:2}; do
			get $TYPE $i
		done
		;;
esac
